### ISSUE TITLE
Bug: Text duplication on non-selected lines

### ISSUE THREAD

**Issue by Steve0Greatness** [WojtekCodesToday/jim#3]
![(See code block #2 below)](https://github.com/WojtekCodesToday/jim/assets/75220768/e74d6b2f-58d3-4968-9e1b-150ee465ffc4)

The displayed file is meant to be

```javascript
function hello() {
  console.log("hello world");
}
hello()
```

But it instead shows

```javascript
function hello() {function hello() {
  console.log("hello world");  console.log("hello world");
}}
hello()hello()
```

This is only a visual bug I believe, as when editing a specific line, this goes away.

**Comment by WojtekCodesToday** [comment]
I know this bug before i published it,
i can't fix it, also i only had that with the last line of index.js so you aren't alone,
it's possible to recode index.js, but it could be an very hard process.

**Comment by WojtekCodesToday** [comment]
Okay i've patched it, but in an unreleased version!
